"""Training script for the Behavioral Transformer (§2C.2).

Trains on synthetic data generated by generate_cheat_data.py.
Uses cosine annealing LR scheduler and checkpoints every 10 epochs.
"""
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import TensorDataset, DataLoader
import sys
import os

# Add server to path so we can import models
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'server')))
from detection.models.transformer import BehavioralTransformer


def get_device() -> torch.device:
    """Select the best available device (CUDA > MPS > CPU)."""
    if torch.cuda.is_available():
        return torch.device("cuda")
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def evaluate(model, dataloader, device):
    """Compute accuracy and per-class recall on the full dataset."""
    model.eval()
    correct = 0
    total = 0
    class_tp = torch.zeros(5)
    class_fn = torch.zeros(5)

    with torch.no_grad():
        for batch_x, batch_y_class, _ in dataloader:
            batch_x = batch_x.to(device)
            batch_y_class = batch_y_class.to(device)

            _, class_pred = model(batch_x)
            predicted = (class_pred > 0.5).float()

            correct += (predicted == batch_y_class).all(dim=1).sum().item()
            total += batch_y_class.size(0)

            # Per-class recall
            for c in range(5):
                positives = batch_y_class[:, c] == 1.0
                class_tp[c] += (predicted[:, c][positives] == 1.0).sum().item()
                class_fn[c] += (predicted[:, c][positives] == 0.0).sum().item()

    accuracy = correct / total if total > 0 else 0.0
    recall = {}
    class_names = ["aim", "reaction", "macro", "speed", "tracking"]
    for c in range(5):
        tp = class_tp[c].item()
        fn = class_fn[c].item()
        recall[class_names[c]] = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    return accuracy, recall


def train_transformer(
    data_path: str = "data/synthetic_transformer.pt",
    epochs: int = 50,
    batch_size: int = 32,
):
    print("Loading synthetic data...")
    data = torch.load(data_path, weights_only=False)
    X = data["X"]
    Y_class = data["Y_class"]
    Y_next = data["Y_next"]

    dataset = TensorDataset(X, Y_class, Y_next)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Initialize Model — n_layers=6 per PRD spec
    device = get_device()
    print(f"Using device: {device}")

    model = BehavioralTransformer(
        input_dim=9, d_model=64, n_heads=4, n_layers=6
    ).to(device)

    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")

    # Losses & Optimizer
    class_criterion = nn.BCELoss()
    next_event_criterion = nn.MSELoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)

    # Cosine Annealing LR Scheduler (per PRD)
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-5)

    # Checkpoint directory
    ckpt_dir = "server/detection/models/weights"
    os.makedirs(ckpt_dir, exist_ok=True)

    print(f"Starting training loop ({epochs} epochs)...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        total_class_loss = 0.0
        total_seq_loss = 0.0

        for batch_x, batch_y_class, batch_y_next in dataloader:
            batch_x = batch_x.to(device)
            batch_y_class = batch_y_class.to(device)
            batch_y_next = batch_y_next.to(device)

            optimizer.zero_grad()

            # Forward pass
            next_pred, class_pred = model(batch_x)

            # Compute losses
            loss_seq = next_event_criterion(next_pred, batch_y_next)
            loss_class = class_criterion(class_pred, batch_y_class)

            # Total loss (weighted sum — classification is 2x more important)
            loss = loss_seq + (loss_class * 2.0)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()
            total_class_loss += loss_class.item()
            total_seq_loss += loss_seq.item()

        # Step the scheduler
        scheduler.step()
        lr = scheduler.get_last_lr()[0]

        avg_loss = total_loss / len(dataloader)
        avg_class = total_class_loss / len(dataloader)
        avg_seq = total_seq_loss / len(dataloader)

        print(
            f"Epoch [{epoch + 1}/{epochs}] | "
            f"Loss: {avg_loss:.4f} (Class: {avg_class:.4f}, Seq: {avg_seq:.4f}) | "
            f"LR: {lr:.6f}"
        )

        # Checkpoint every 10 epochs
        if (epoch + 1) % 10 == 0:
            ckpt_path = os.path.join(ckpt_dir, f"transformer_epoch{epoch + 1}.pt")
            torch.save(model.state_dict(), ckpt_path)
            print(f"  ✓ Checkpoint saved: {ckpt_path}")

            # Evaluate
            accuracy, recall = evaluate(model, dataloader, device)
            print(f"  ✓ Accuracy: {accuracy:.2%}")
            for name, rec in recall.items():
                print(f"    {name}: {rec:.2%}")

    # Save final model
    final_path = os.path.join(ckpt_dir, "transformer_v1.pt")
    torch.save(model.state_dict(), final_path)
    print(f"\nFinal model saved to {final_path}")

    # Final evaluation
    accuracy, recall = evaluate(model, dataloader, device)
    print(f"\nFinal Accuracy: {accuracy:.2%}")
    for name, rec in recall.items():
        print(f"  {name} recall: {rec:.2%}")


if __name__ == "__main__":
    train_transformer()
