"""Training script for the Behavioral Mesh GAT (§2C.2).

Trains on synthetic graph data generated by generate_mesh_data.py.
Uses cosine annealing LR scheduler and checkpoints every 10 epochs.
"""
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch_geometric.loader import DataLoader
import sys
import os

# Add server to path so we can import models
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'server')))
from detection.models.gat import BehavioralMeshGAT


def get_device() -> torch.device:
    """Select the best available device (CUDA > MPS > CPU)."""
    if torch.cuda.is_available():
        return torch.device("cuda")
    elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def evaluate(model, dataloader, device):
    """Compute per-class recall and false positive rate."""
    model.eval()
    class_tp = torch.zeros(2)
    class_fp = torch.zeros(2)
    class_fn = torch.zeros(2)
    class_tn = torch.zeros(2)

    with torch.no_grad():
        for batch in dataloader:
            batch = batch.to(device)
            out = model(batch.x, batch.edge_index, batch.edge_attr, batch.batch)
            predicted = (out > 0.5).float()
            labels = batch.y

            for c in range(2):
                positives = labels[:, c] == 1.0
                negatives = labels[:, c] == 0.0
                class_tp[c] += (predicted[:, c][positives] == 1.0).sum().item()
                class_fn[c] += (predicted[:, c][positives] == 0.0).sum().item()
                class_fp[c] += (predicted[:, c][negatives] == 1.0).sum().item()
                class_tn[c] += (predicted[:, c][negatives] == 0.0).sum().item()

    results = {}
    class_names = ["wallhack", "collab"]
    for c in range(2):
        tp, fp, fn, tn = class_tp[c].item(), class_fp[c].item(), class_fn[c].item(), class_tn[c].item()
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
        results[class_names[c]] = {"recall": recall, "fpr": fpr}

    return results


def train_gat(
    data_path: str = "data/synthetic_gat.pt",
    epochs: int = 50,
    batch_size: int = 32,
):
    print("Loading synthetic graph data...")
    dataset = torch.load(data_path, weights_only=False)

    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Initialize Model — expanded features per PRD
    device = get_device()
    print(f"Using device: {device}")

    model = BehavioralMeshGAT(
        node_features=12,
        edge_features=4,
        hidden_channels=32,
        heads=4,
        out_classes=2,
    ).to(device)

    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")

    # Loss & Optimizer
    criterion = nn.BCELoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)

    # Cosine Annealing LR Scheduler (per PRD)
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-5)

    # Checkpoint directory
    ckpt_dir = "server/detection/models/weights"
    os.makedirs(ckpt_dir, exist_ok=True)

    print(f"Starting training loop ({epochs} epochs)...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0

        for batch in dataloader:
            batch = batch.to(device)

            optimizer.zero_grad()

            # Forward pass
            out = model(batch.x, batch.edge_index, batch.edge_attr, batch.batch)

            # Compute loss
            loss = criterion(out, batch.y)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            total_loss += loss.item()

        # Step the scheduler
        scheduler.step()
        lr = scheduler.get_last_lr()[0]

        avg_loss = total_loss / len(dataloader)
        print(f"Epoch [{epoch + 1}/{epochs}] | Loss: {avg_loss:.4f} | LR: {lr:.6f}")

        # Checkpoint every 10 epochs
        if (epoch + 1) % 10 == 0:
            ckpt_path = os.path.join(ckpt_dir, f"gat_epoch{epoch + 1}.pt")
            torch.save(model.state_dict(), ckpt_path)
            print(f"  ✓ Checkpoint saved: {ckpt_path}")

            # Evaluate
            results = evaluate(model, dataloader, device)
            for name, metrics in results.items():
                print(f"  ✓ {name}: recall={metrics['recall']:.2%}, FPR={metrics['fpr']:.2%}")

    # Save final model
    final_path = os.path.join(ckpt_dir, "gat_v1.pt")
    torch.save(model.state_dict(), final_path)
    print(f"\nFinal model saved to {final_path}")

    # Final evaluation
    results = evaluate(model, dataloader, device)
    print("\nFinal Metrics:")
    for name, metrics in results.items():
        print(f"  {name}: recall={metrics['recall']:.2%}, FPR={metrics['fpr']:.2%}")


if __name__ == "__main__":
    train_gat()
